### ISSUE TITLE
Can I see an example on how to use MD5 on multiple js files at once?

### ISSUE THREAD

**Issue by lty83** [shakyShane/grunt-cache-breaker#10]
I know i'm probably totally off here.. but this is what i'm trying to do:

```js
cachebreaker: {
		dev: {
			options: {
				match: ['vendors.js', 'app.js', 'directives.js' , 'services.js', 'controllers.js'],
				replacement: 'md5',
				src: {
					path: [ 
							'../scripts_final/vendors.js', 
							'../scripts_final/app.js', 
							'../scripts_final/directives.js', 
							'../scripts_final/services.js', 
							'../scripts_final/controllers.js', 
						  ]
				}
			},
			files: {
				src: ['../index.html']
			}
		}
```

What am I doing wrong?

**Comment by ejzy** [comment]
+1

**Comment by guitarfish** [comment]
I'd like to know this as well...

**Comment by madhu131313** [comment]
can u please add this to documentation or somewhere, i think real projects need this. 
path as an array thing or make single path to be compulsory array, so that people understand that intutively.

**Comment by madhu131313** [comment]
+100

**Comment by shakyShane** [comment]
Please look at https://github.com/shakyShane/grunt-cache-breaker/blob/master/Gruntfile.js#L56-L69 (and the udated readme.md) to see how this is done in `2.0.0` available now.
