### ISSUE TITLE
Replace ?rel=

### ISSUE THREAD

**Issue by K4T** [shakyShane/grunt-cache-breaker#11]
Hi, I would like to have ability to replace ?rel= param to something different, for example ?v= etc.
Is it possible? Or can you add that possibility?

**Comment by shakyShane** [comment]
Of course, `replacement` can be a function that you provide.

js: {
                options: {
                    match: ['script.js', 'app.js'],
                    replacement: function () {
                        return "123456"; // return anything you want here
                    }
                },
                files: {
                    'test/fixtures/query.out.html': ["test/fixtures/query.html"]
                }
            },

**Comment by realph** [comment]
I think he's asking how to change `?rel=` to `?v=`. Is this at all possible?

**Comment by K4T** [comment]
+1
