### ISSUE TITLE
Not workig

### ISSUE THREAD

**Issue by djindjic** [shakyShane/grunt-cache-breaker#8]
Sorry, but it's not working for me. I guess it should make application.min.js with md5 hash in filename when I run grunt build? In my case everything is same like before I installed your plugin.

**Comment by zero-distraction** [comment]
The plugin works very well to change the references to the file names. It's not very clear *whether it actually does anything to the actual file*. For example, if you have a file named `application.min` and expected it would be changed to `application.md5.min` it just doesn't happen. In my opinion the query string mode, is much easier to setup and still effective to remove cache.

**Comment by shakyShane** [comment]
@djindjic - sorry for the delay. 

@zero-distraction is correct - this plugin **does not** alter the actual filename on disk. 

If you want something that actually changes the filename, perhaps something like https://github.com/yeoman/grunt-filerev may serve you better :)
